"""Template for CONTRACTS.md (shared interface definitions)."""

from __future__ import annotations

from ...models import DiscoveryContext


def render_contracts_md(ctx: DiscoveryContext) -> str:
    """Render CONTRACTS.md for cross-module interface definitions.

    Only generated when coordination_complexity >= 2.
    """
    # Group deps by interface type
    by_type: dict[str, list[tuple[str, str, str]]] = {}
    for d in ctx.cross_deps:
        by_type.setdefault(d.interface_type, []).append((d.from_module, d.to_module, d.description))

    sections = [_header(ctx)]

    # API contracts
    api_deps = by_type.get("api", [])
    if api_deps:
        sections.append(_api_section(api_deps))

    # File-based exchanges
    file_deps = by_type.get("file", [])
    if file_deps:
        sections.append(_file_section(file_deps))

    # Database contracts
    db_deps = by_type.get("database", [])
    if db_deps:
        sections.append(_db_section(db_deps))

    # Environment variables
    env_deps = by_type.get("env_var", [])
    if env_deps:
        sections.append(_env_section(env_deps))

    # Message queue contracts
    mq_deps = by_type.get("message_queue", [])
    if mq_deps:
        sections.append(_mq_section(mq_deps))

    # If no deps were categorized, add a generic section
    if len(sections) == 1:
        sections.append(_generic_section(ctx))

    sections.append(_footer())

    return "\n".join(sections)


def _header(ctx: DiscoveryContext) -> str:
    return f"""\
# {ctx.project_name} — Cross-Module Contracts

> This file is the single source of truth for all cross-module interfaces.
> All modules reference this file. Update it when interfaces change.
> Last updated: (auto-generated by lindy-orchestrate onboard)
"""


def _api_section(deps: list[tuple[str, str, str]]) -> str:
    rows = []
    for from_mod, to_mod, desc in deps:
        rows.append(f"| {from_mod} → {to_mod} | {desc} | (define endpoints) |")
    table = "\n".join(rows)
    return f"""\
## API Contracts

| Dependency | Description | Endpoints |
|-----------|-------------|-----------|
{table}

<!-- Define API endpoints, request/response formats here -->
"""


def _file_section(deps: list[tuple[str, str, str]]) -> str:
    rows = []
    for from_mod, to_mod, desc in deps:
        rows.append(f"| {from_mod} → {to_mod} | {desc} | (define path) | (define format) |")
    table = "\n".join(rows)
    return f"""\
## File-Based Data Exchange

| Dependency | Description | Path | Format |
|-----------|-------------|------|--------|
{table}
"""


def _db_section(deps: list[tuple[str, str, str]]) -> str:
    rows = []
    for from_mod, to_mod, desc in deps:
        rows.append(f"| {from_mod} → {to_mod} | {desc} | (define tables) |")
    table = "\n".join(rows)
    return f"""\
## Database Contracts

| Dependency | Description | Tables/Views |
|-----------|-------------|--------------|
{table}
"""


def _env_section(deps: list[tuple[str, str, str]]) -> str:
    rows = []
    for from_mod, to_mod, desc in deps:
        rows.append(f"| {from_mod} → {to_mod} | {desc} | (define variables) |")
    table = "\n".join(rows)
    return f"""\
## Environment Variable Contracts

| Dependency | Description | Variables |
|-----------|-------------|-----------|
{table}
"""


def _mq_section(deps: list[tuple[str, str, str]]) -> str:
    rows = []
    for from_mod, to_mod, desc in deps:
        rows.append(f"| {from_mod} → {to_mod} | {desc} | (define topics) |")
    table = "\n".join(rows)
    return f"""\
## Message Queue Contracts

| Dependency | Description | Topics/Queues |
|-----------|-------------|---------------|
{table}
"""


def _generic_section(ctx: DiscoveryContext) -> str:
    mod_names = ", ".join(m.name for m in ctx.modules)
    return f"""\
## Interfaces

Modules: {mod_names}

<!-- Define shared interfaces, schemas, and data exchange formats here.
     Examples:
     - API endpoint contracts (request/response shapes)
     - Shared data types and enums
     - File format specifications
     - Environment variable agreements
-->
"""


def _footer() -> str:
    return """\
---

## Change Protocol

1. Propose changes in a Cross-Module Request (STATUS.md)
2. Get approval from affected module owners
3. Update this file FIRST, then update implementations
4. Run integration tests to verify contract compliance
"""
