"""Clear command — removes all orchestrator scaffold files."""

from __future__ import annotations

import shutil
from pathlib import Path

import typer
from rich.console import Console


def _is_orchestrator_claude_md(path: Path) -> bool:
    """Check if a CLAUDE.md was generated by orchestrator (mentions Agent or STATUS.md)."""
    try:
        lines = path.read_text(encoding="utf-8").splitlines()[:5]
        text = "\n".join(lines)
        return "Agent" in text or "STATUS.md" in text
    except (OSError, UnicodeDecodeError):
        return False


def _find_module_legacy_files(cwd: Path) -> list[Path]:
    """Find per-module legacy files (STATUS.md, orchestrator-generated CLAUDE.md)."""
    results: list[Path] = []
    for child in sorted(cwd.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        status = child / "STATUS.md"
        claude = child / "CLAUDE.md"
        if status.exists():
            results.append(status)
        if claude.exists() and _is_orchestrator_claude_md(claude):
            results.append(claude)
    return results


def _clean_gitignore(cwd: Path) -> bool:
    """Remove .orchestrator / orchestrator lines from .gitignore. Returns True if modified."""
    gitignore = cwd / ".gitignore"
    if not gitignore.exists():
        return False
    original = gitignore.read_text(encoding="utf-8")
    lines = original.splitlines(keepends=True)
    filtered = [
        ln
        for ln in lines
        if ".orchestrator" not in ln and "orchestrator" not in ln.lower().split("#")[0]
    ]
    new_text = "".join(filtered)
    if new_text == original:
        return False
    gitignore.write_text(new_text, encoding="utf-8")
    return True


def register_clear_command(app: typer.Typer, console: Console) -> None:
    """Register the clear command on the Typer app."""

    @app.command()
    def clear(
        force: bool = typer.Option(False, "--force", "-f", help="Skip confirmation"),
    ) -> None:
        """Remove all orchestrator scaffold files (.orchestrator/, legacy configs)."""
        cwd = Path.cwd()
        targets: list[Path] = []

        # .orchestrator/ directory
        orch_dir = cwd / ".orchestrator"
        if orch_dir.exists():
            targets.append(orch_dir)

        # Legacy root files
        legacy_files = ["orchestrator.yaml", "CLAUDE.md", "ARCHITECTURE.md", "CONTRACTS.md"]
        for name in legacy_files:
            p = cwd / name
            if p.exists():
                targets.append(p)

        # Legacy docs/agents/ directory
        agents_dir = cwd / "docs" / "agents"
        if agents_dir.exists():
            targets.append(agents_dir)

        # Per-module legacy files
        module_files = _find_module_legacy_files(cwd)
        targets.extend(module_files)

        if not targets:
            console.print("No orchestrator files found.")
            raise typer.Exit(0)

        # List what will be deleted
        console.print("[bold]The following will be deleted:[/]\n")
        for t in targets:
            rel = t.relative_to(cwd)
            label = f"  {rel}/" if t.is_dir() else f"  {rel}"
            console.print(label)

        console.print()

        if not force:
            typer.confirm("Proceed with deletion?", abort=True)

        # Delete
        for t in targets:
            if t.is_dir():
                shutil.rmtree(t)
            else:
                t.unlink()

        # Clean .gitignore
        if _clean_gitignore(cwd):
            console.print("[dim]Cleaned .gitignore entries.[/]")

        console.print("[bold green]Orchestrator files removed.[/]")
