"""Artifact generator — produces all organizational files from a DiscoveryContext.

Generates: orchestrator.yaml, CLAUDE.md (root + per-module), CONTRACTS.md, STATUS.md.
"""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

from ..models import DiscoveryContext
from ..status.templates import generate_status_md
from .templates.agent_docs import render_agent_docs
from .templates.architecture_md import render_architecture_md
from .templates.contracts_md import render_contracts_md
from .templates.module_claude_md import render_module_claude_md
from .templates.root_claude_md import render_root_claude_md

console = Console()


def generate_artifacts(
    ctx: DiscoveryContext,
    output_dir: Path,
    force: bool = False,
) -> list[Path]:
    """Generate all organizational artifacts from the discovery context.

    Returns a list of paths that were written.
    """
    output_dir = output_dir.resolve()
    written: list[Path] = []

    orch_dir = output_dir / ".orchestrator"

    # 1. orchestrator.yaml → .orchestrator/config.yaml
    config_content = _render_config(ctx)
    written.extend(_write_file(orch_dir / "config.yaml", config_content, force))

    # 2. Root CLAUDE.md → .orchestrator/claude/root.md
    root_claude = render_root_claude_md(ctx)
    written.extend(_write_file(orch_dir / "claude" / "root.md", root_claude, force))

    # 3. Per-module CLAUDE.md → .orchestrator/claude/{mod.name}.md
    for mod in ctx.modules:
        mod_claude = render_module_claude_md(ctx, mod)
        written.extend(_write_file(orch_dir / "claude" / f"{mod.name}.md", mod_claude, force))

    # 3b. Codex mirror: .orchestrator/codex/ (identical content for codex_cli provider)
    written.extend(_write_file(orch_dir / "codex" / "root.md", root_claude, force))
    for mod in ctx.modules:
        mod_claude = render_module_claude_md(ctx, mod)
        written.extend(_write_file(orch_dir / "codex" / f"{mod.name}.md", mod_claude, force))

    # 4. CONTRACTS.md → .orchestrator/contracts.md (only for moderate+ complexity)
    if ctx.coordination_complexity >= 2:
        contracts = render_contracts_md(ctx)
        written.extend(_write_file(orch_dir / "contracts.md", contracts, force))

    # 5. ARCHITECTURE.md → .orchestrator/architecture.md
    architecture = render_architecture_md(ctx)
    written.extend(_write_file(orch_dir / "architecture.md", architecture, force))

    # 6. docs/agents/ → .orchestrator/docs/
    agent_docs = render_agent_docs(ctx)
    docs_dir = orch_dir / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    for filename, content in agent_docs.items():
        written.extend(_write_file(docs_dir / filename, content, force))

    # 7. Per-module STATUS.md → .orchestrator/status/{mod.name}.md
    for mod in ctx.modules:
        status_path = orch_dir / "status" / f"{mod.name}.md"
        if not status_path.exists() or force:
            status_path.parent.mkdir(parents=True, exist_ok=True)
            content = generate_status_md(mod.name)
            written.extend(_write_file(status_path, content, force))

    # 8. Runtime directories
    (orch_dir / "logs").mkdir(parents=True, exist_ok=True)
    (orch_dir / "sessions").mkdir(parents=True, exist_ok=True)

    # 9. Update .gitignore
    _update_gitignore(output_dir)

    return written


# ---------------------------------------------------------------------------
# orchestrator.yaml rendering
# ---------------------------------------------------------------------------


def _render_config(ctx: DiscoveryContext) -> str:
    """Render orchestrator.yaml from the discovery context."""
    lines = [
        "# orchestrator.yaml — generated by lindy-orchestrate onboard",
        "",
        "project:",
        f'  name: "{ctx.project_name}"',
        f'  branch_prefix: "{ctx.branch_prefix}"',
        "",
        "modules:",
    ]

    for mod in ctx.modules:
        lines.append(f"  - name: {mod.name}")
        lines.append(f"    path: {mod.path}/")

        # Add repo if we can extract from git remote
        if ctx.git_remote:
            repo = _extract_repo_slug(ctx.git_remote)
            if repo:
                lines.append(f"    repo: {repo}")

        # Add CI workflow if detected
        ci_file = _detect_module_ci(mod)
        if ci_file:
            lines.append(f"    ci_workflow: {ci_file}")

        lines.append("")

    lines.extend(
        [
            "planner:",
            "  mode: cli  # cli | api",
            "  # model: claude-sonnet-4-20250514  # for api mode",
            "",
            "dispatcher:",
            "  timeout_seconds: 1800",
            "  permission_mode: bypassPermissions",
            "",
        ]
    )

    # QA gates from detected commands
    qa_gates = _build_qa_gates(ctx)
    if qa_gates:
        lines.append("qa_gates:")
        lines.append("  custom:")
        for gate in qa_gates:
            lines.append(f"    - name: {gate['name']}")
            lines.append(f'      command: "{gate["command"]}"')
            lines.append(f'      cwd: "{gate["cwd"]}"')
            if gate.get("timeout"):
                lines.append(f"      timeout: {gate['timeout']}")
            if gate.get("required") == "false":
                lines.append("      required: false")
            if gate.get("diff_only") == "true":
                lines.append("      diff_only: true")
        lines.append("")

    lines.extend(
        [
            "safety:",
            "  dry_run: false",
            "  max_retries_per_task: 2",
            "  max_parallel: 10",
        ]
    )

    return "\n".join(lines) + "\n"


def _extract_repo_slug(remote_url: str) -> str:
    """Extract org/repo from a git remote URL."""
    # SSH: git@github.com:org/repo.git
    if ":" in remote_url and "@" in remote_url:
        path = remote_url.split(":")[-1]
        return path.removesuffix(".git")
    # HTTPS: https://github.com/org/repo.git
    if "github.com" in remote_url or "gitlab.com" in remote_url:
        parts = remote_url.rstrip("/").split("/")
        if len(parts) >= 2:
            repo = parts[-1].removesuffix(".git")
            org = parts[-2]
            return f"{org}/{repo}"
    return ""


def _detect_module_ci(mod) -> str:
    """Detect CI workflow file for a module."""
    # The CI is usually at root level, not per-module
    # Return a reasonable default
    return "ci.yml"


def _build_qa_gates(ctx: DiscoveryContext) -> list[dict[str, str]]:
    """Build QA gate configurations from discovery context.

    Smart classification:
    - Go tests: split into fast (-short) required + full (required: false)
    - Lint/format commands: add diff_only: true
    - Playwright/e2e: mark required: false with longer timeout
    - pytest: add -x --tb=short for fast feedback
    """
    gates: list[dict[str, str]] = []
    for mod_name, commands in ctx.qa_requirements.items():
        for cmd in commands:
            clean_cmd = cmd.split("  #")[0].strip()
            gates.extend(_classify_gate(mod_name, clean_cmd))
    return gates


def _classify_gate(mod_name: str, cmd: str) -> list[dict[str, str]]:
    """Classify a command into one or more smart QA gates."""
    # Go test: split into fast (-short) + full (optional)
    if cmd == "go test ./...":
        return [
            {
                "name": f"{mod_name}-test-fast",
                "command": "go test ./... -short -count=1",
                "cwd": "{module_path}",
                "timeout": "120",
            },
            {
                "name": f"{mod_name}-test-full",
                "command": "go test ./... -count=1",
                "cwd": "{module_path}",
                "timeout": "600",
                "required": "false",
            },
        ]

    # pytest: add fast flags
    if cmd == "pytest":
        return [
            {
                "name": f"{mod_name}-pytest",
                "command": "pytest -x -q --tb=short",
                "cwd": "{module_path}",
            }
        ]

    # Cargo test: split fast/full
    if cmd == "cargo test":
        return [
            {
                "name": f"{mod_name}-test",
                "command": "cargo test",
                "cwd": "{module_path}",
            }
        ]

    # Playwright/e2e: optional with longer timeout
    if "playwright" in cmd.lower() or "e2e" in cmd.lower() or "cypress" in cmd.lower():
        return [
            {
                "name": f"{mod_name}-{_slugify(cmd)}",
                "command": cmd,
                "cwd": "{module_path}",
                "timeout": "600",
                "required": "false",
            }
        ]

    # Lint/format commands: add diff_only
    if _is_lint_command(cmd):
        return [
            {
                "name": f"{mod_name}-{_slugify(cmd)}",
                "command": cmd,
                "cwd": "{module_path}",
                "diff_only": "true",
            }
        ]

    # Default: as-is
    return [
        {
            "name": f"{mod_name}-{_slugify(cmd)}",
            "command": cmd,
            "cwd": "{module_path}",
        }
    ]


def _is_lint_command(cmd: str) -> bool:
    """Check if a command is a linter/formatter."""
    lint_keywords = (
        "eslint",
        "prettier",
        "ruff check",
        "ruff format",
        "mypy",
        "pyright",
        "tsc --noEmit",
        "go vet",
        "clippy",
        "npm run lint",
        "npm run format",
        "biome",
        "oxlint",
    )
    return any(kw in cmd.lower() for kw in lint_keywords)


def _slugify(text: str) -> str:
    """Create a simple slug from a command string."""
    # Take first word after common prefixes
    text = text.replace("npx ", "").replace("npm run ", "").replace("npm ", "")
    parts = text.split()
    if parts:
        slug = parts[0].replace(".", "").replace("/", "")
        return slug[:20]
    return "check"


# ---------------------------------------------------------------------------
# File writing helpers
# ---------------------------------------------------------------------------


def _write_file(path: Path, content: str, force: bool) -> list[Path]:
    """Write a file, handling conflicts. Returns list of written paths."""
    if path.exists() and not force:
        console.print(f"  [dim]{path.name} already exists, skipping[/]")
        return []

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

    rel = path.name
    try:
        rel = str(path.relative_to(Path.cwd()))
    except ValueError:
        pass
    console.print(f"  [green]Created {rel}[/]")
    return [path]


def _update_gitignore(root: Path) -> None:
    """Ensure .gitignore has orchestrator entry."""
    gitignore = root / ".gitignore"
    entry = ".orchestrator/"

    if gitignore.exists():
        existing = gitignore.read_text(encoding="utf-8")
        if entry not in existing:
            with gitignore.open("a", encoding="utf-8") as f:
                f.write(f"\n# lindy-orchestrator\n{entry}\n")
    else:
        gitignore.write_text(
            f"# lindy-orchestrator\n{entry}\n",
            encoding="utf-8",
        )
